ekf_node:
  ros__parameters:
    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "catamaran/base_link"
    world_frame: "odom" #parent of utm / or child
    frequency: 30.0
    two_d_mode: true
    publish_tf: true

    sensors: ["odom", "imu", "gps"]
    odom0: "/odom"
    odom0_config: [true, true, false, 
                   false, false, true, 
                   false, false, false, 
                   false, false, true]
    imu0: "/catamaran/sensors/imu/imu/data"
    imu0_config: [false, false, false,
                  true, true, true, 
                  false, false, false, 
                  false, false, true]

    # Tutorial has this split in two files
    # gps0: "/catamaran/sensors/gps/gps/fix"
    gps0: "/odometry/gps"
    gps0_config: [true, true, false, 
                  false, false, false, 
                  false, false, false, 
                  false, false, false]