amcl:
  ros__parameters:
    use_sim_time: true
    base_frame_id: "catamaran/base_link"
    odom_frame_id: "odom"
    global_frame_id: "map"

bt_navigator:
  ros__parameters:
    global_frame_id: "map"
    robot_base_frame: "catamaran/base_link"

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0

controller_server:
  ros__parameters:
    expected_controller_frequency: 20.0