# amcl:
#   ros__parameters:
#     use_sim_time: true
#     base_frame_id: "catamaran/base_link"
#     odom_frame_id: odom
#     global_frame_id: map

bt_navigator:
  ros__parameters:
    global_frame_id: map
    robot_base_frame: "catamaran/base_link"

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0

controller_server:
  ros__parameters:
    expected_controller_frequency: 20.0
    controller_plugins: ["FollowPath"]  # Use the DWB controller
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      # Required critics
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      # Other DWB parameters
      max_vel_x: 0.5
      min_vel_x: -0.5
      max_vel_y: 0.0
      min_vel_y: 0.0
      max_vel_theta: 1.0
      min_vel_theta: -1.0
      acc_lim_x: 1.0
      acc_lim_y: 0.0
      acc_lim_theta: 1.0

global_costmap:
  global_costmap:
    ros_parameters:
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]